name: advtrains

on:
  schedule:
    - cron:  '0 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: mirror
      run: ./mirror.sh http://git.bananach.space/advtrains.git git@github.com:minetest-mirrors/advtrains.git master
